### ISSUE TITLE
Add fate dice as a type

### ISSUE THREAD

**Issue by jacebenson** [meadsteve/DiceApi#12]

**Comment by meadsteve** [comment]
At the moment there's an implicit assumption in pieces of the code used for rendering (and building) that size is the only way of identifying a kind of dice. It might be nice to fix this and add fate dice (and any other special kind of dice).

**Comment by meadsteve** [comment]
I've done the first part of this for more non numeric dice here: https://github.com/meadsteve/DiceApi/blob/master/src/Dice/DiceGenerator.php#L32

However there will need to be some tidy up of the generator to make new kinds of dice more "pluggable".

**Comment by jacebenson** [comment]
Thats great.  I'm not sure how I can contribute but appreciate the fast feedback.

**Comment by meadsteve** [comment]
It's a year later than you asked for but I added (json) fate dice.
http://roll.diceapi.com/json/dfate
https://github.com/meadsteve/DiceApi/pull/15/files
