### ISSUE TITLE
access-control header

### ISSUE THREAD

**Issue by Badlapje** [meadsteve/DiceApi#13]
Hi, 

can you add an access-control header to allow CORS requests?  As it stands now i'd need to make a JSONP request.  As such that is fine, but i'd like to use the api in an exercise for students where they can simply make a fetch request, rather than a jsonp request.

Cheers!
koen

**Comment by meadsteve** [comment]
hey @Badlapje sorry. I totally missed this request. I've added a * allow on the dice requests https://github.com/meadsteve/DiceApi/pull/14.

~ Steve
