### ISSUE TITLE
Facebook login integration

### ISSUE THREAD

**Issue by jnewc** [meadsteve/DiceApi#3]
High priority though, amirite?

**Comment by meadsteve** [comment]
well this will be required for my dating app which matches people based on what kind of dice they like to roll.

**Comment by ConnorVG** [comment]
I rate this issue `GET http://roll.diceapi.com/d6` out of 6.

**Comment by meadsteve** [comment]
I haven't found a micro-service deployment tool that's webscale enough to productionize this feature yet.

**Comment by ConnorVG** [comment]
did someone say scale? as-in maximum four hexadimensional scalage for untrilimited availabalimities?

**Comment by meadsteve** [comment]
Great now all I can think of is [this](https://www.youtube.com/watch?v=rLDgQg6bq7o)

**Comment by ConnorVG** [comment]
Oh no... _What have you done_!?
